"""add email to students

Revision ID: 10552db8b3b7
Revises: 45d6866116e0
Create Date: 2026-08-24 08:11:55.479635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10552db8b3b7'
down_revision: Union[str, Sequence[str], None] = '45d6866116e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.String(), nullable=True))
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'course',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'course',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('students', 'email')
    # ### end Alembic commands ###
